name: trafficon_postgis_docker

volumes:
  trafficon-postgis-vol:

services:
  postgis:
    image: kartoza/postgis:16-3
    volumes:
      - trafficon-postgis-vol:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=exampledb
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - 5432:5432
    restart: on-failure