# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-alpine

# Add Maintainer Info
LABEL maintainer="maintainer@example.com"

# Set the working directory inside the container
WORKDIR /app

# Define build-time argument for the application's JAR file location
ARG JAR_FILE=target/weatherservice-0.0.1-SNAPSHOT.jar

# Copy the JAR file from the host into the container
COPY ${JAR_FILE} app.jar

# Expose the port that the application will run on
EXPOSE 8080

# Set environment variables
ENV JAVA_OPTS=""

# Run the application
ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar /app/app.jar"]
